## src/main/resources/config.yml
world-name: world
game:
  difficulty: HARD
  initial-border:
    center-x: 0.0
    center-z: 0.0
    size: 4000.0

start-settings:
  clear-inventory: true
  clear-ender-chest: true
  health: 20.0
  food-level: 20
  level: 0
  experience: 0.0
  spawn-slowness:
    enabled: true
    duration: 10
    amplifier: 10

messages:
  config-reloaded: "§aConfig je uspješno učitan."
  uhc-started: "§aUHC je počeo!"
  uhc-ended: "§cUHC je završen."
  not-enough-spawns: "§cNema dovoljno spawn lokacija za sve igrače."
  loot-table-missing: "§cSupply drop loot table ne postoji."

start-countdown:
  seconds: 15
  intro-title: "§6Dobro dosli u UHC sezone 6"
  intro-subtitle: "§eFloxyCrafta"
  intro-duration-seconds: 3
  title: " "
  subtitle: "§fUHC pocinje za §e{seconds} §fsekundi"
  started-title: "§aUHC JE POČEO!"
  started-subtitle: "§fSretno svima!"

winner-announcement:
  title: "§6{player}"
  subtitle: "§eje osvojio Floxy UHC Sezona 6"
  fade-in-ticks: 5
  stay-ticks: 100
  fade-out-ticks: 5

results:
  header: "§6§l■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■"
  title: "             §6§lFloxyCraft Sezona 6 UHC"
  winner-line: "       §ePobjednik: {player}"
  first-killer-line: "   §#FFAA001. {player} §7- §7{kills} killova"
  second-killer-line: "   §#CECACA2. {player} §7- §7{kills} killova"
  third-killer-line: "   §#B4684D3. {player} §7- §7{kills} killova"
  honorable-mentions-title: "      §6Honorable mentions:"
  honorable-mention-line: "   §7- {player} §7- {kills} killova"
  footer: "§6§l■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■"

spawn-locations:
  - {X: 0.5, Y: 98, Z: 0.5, yaw: 0.0, pitch: 0.0}
  - {X: 1.5, Y: 98, Z: 1.5, yaw: 0.0, pitch: 0.0}
  - {X: -1.5, Y: 98, Z: -1.5, yaw: 0.0, pitch: 0.0}
  - {X: 2.5, Y: 98, Z: 2.5, yaw: 0.0, pitch: 0.0}
  - {X: -2.5, Y: 98, Z: -2.5, yaw: 0.0, pitch: 0.0}

## Gapple limit
golden-apple-limit: 3
golden-apple-limit-warning-message: "Dosao si do limita zlatnih jabuka!"
golden-apple-limit-reached-message: "Dostigao si limit zlatnih jabuka!"
border-movement-start-message: "Border se pokrenuo!"
border-movement-start-warning-message: "Border ce se pokrenuti za {seconds} sekundi!"
border-warnings:
  enabled: true
  times: [30, 10, 3, 2, 1]

banned-item-removal-message: "Pokupio si nedozvoljeni item (%s) pa smo ti ga maznli <3"
banned-items:
  - DIAMOND_SWORD
  - NETHERITE_AXE
  - TOTEM_OF_UNDYING

# Loot tables for supply drops
supply-drop-loot-table: minecraft:chests/desert_pyramid
supply-drop-schematic: balon2.schem
supply-drop-droping-speed: 0.05
supply-drop-landing-message: "§aSupply drop je pao na: §f{x}, {y}, {z}!"
supply-drop-opened-message: "§eSupply drop je otvoren!"
supply-drop:
  glowing: true
  compass-bar-enabled: true
  beacon-enabled: true

# Winner ceremony
winner-ceremony-winner-teleport:
  - {X: 9.0, Y: 99.0, Z: 0.0, yaw: 90.0, pitch: 20.0}
winner-ceremony-spectator-teleport:
  - {X: 5.0, Y: 98.0, Z: 0.0, yaw: -90.0, pitch: -10.0}

winner-ceremony:
  fireworks:
    enabled: true
    waves: 10
    fireworks-per-wave: 6
    interval-ticks: 40
    power: 0

# Scheduled actions
scheduled-actions:
  - time: "0:00:10"
    action: "border"
    params: {X: 0.0, Z: 0.0, size: 100.0, delay: 10, duration: 30}
  - time: "0:00:30"
    action: "supplydrop"
    params: {X: 10.0, Y: 165.0, Z: 10.0}