## src/main/resources/config.yml
world-name: world
spawn-locations:
  - {X: 0, Y: 98, Z: 0}
  - {X: 1, Y: 98, Z: 1}
  - {X: -1, Y: 98, Z: -1}
  - {X: 2, Y: 98, Z: 2}
  - {X: -2, Y: 98, Z: -2}

## Gapple limit
max-golden-apples: 3
gapple-limit-warning-message: "Dosao si do limita zlatnih jabuka!"

## Border movements
# X, Z - center of the border movement (in blocks)
# size - size of the border (radius)
# delay - delay before the border starts moving (in seconds)
# duration - duration of the border movement (in seconds)
border-movements:
  - {X: 0.0, Z: 0.0, size: 10.0, delay: 10, duration: 10}
  - {X: 0.0, Z: 10.0, size: 10.0, delay: 3, duration: 10}
  - {X: 10.0, Z: 10.0, size: 20.0, delay: 3, duration: 10}
  - {X: 10.0, Z: 0.0, size: 20.0, delay: 3, duration: 10}
  - {X: 10.0, Z: -10.0, size: 20.0, delay: 3, duration: 10}
  - {X: 0.0, Z: -10.0, size: 10.0, delay: 3, duration: 10}
  - {X: -10.0, Z: -10.0, size: 10.0, delay: 3, duration: 10}
  - {X: -10.0, Z: 0.0, size: 10.0, delay: 3, duration: 10}
  - {X: -10.0, Z: 10.0, size: 10.0, delay: 3, duration: 10}
  - {X: 0.0, Z: 10.0, size: 10.0, delay: 3, duration: 10}
  - {X: 0.0, Z: 0.0, size: 10.0, delay: 3, duration: 10}

border-movement-start-message: "Border se pokrenuo!"
border-movement-start-warning-message: "Border ce se pokrenuti za {seconds} sekundi!"
border-movement-start-warning-times: [30, 10, 3, 2, 1]

