name: UHC
main: me.ean.Main
version: 1.0
api-version: 1.20
depend:
  - WorldEdit

softdepend: ["PlaceholderAPI"] #



commands:
  testborder:
    description: testiram border
    permission: op
  startuhc:
    description: start uhc
    permission: op
  resetstate:
    description: resetstate
    permission: op
  bacisupplydrop:
    description: supplyaj drop
    permission: op
  enduhc:
    description: end uhc
    permission: op
  configreload:
    description: reloaduj config
    permission: op
  winnerceremony:
    description: testiram winner ceremony
    permission: op
  sb:
    description: pokazujem scoreboard
    permission: op